version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  locker_room:
    build:
      context: ./locker_room
      dockerfile: Dockerfile
    container_name: locker_room
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: "mongodb://admin:password@mongodb:27017"
    command: ["./locker_room"]
  
  general_manager:
    build:
      context: ./general_manager
      dockerfile: Dockerfile
    container_name: general_manager
    depends_on:
      - locker_room
    command: ["./general_manager"]
