[package]
name = "general_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
pssstt = { git = "https://github.com/AminAcer/pssstt", branch = "main" }
tokio = {version = "1", features = ["full"]}
